# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install dependencies
WORKDIR /app
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (optional)
# EXPOSE 3000

# Start the MCP server
CMD ["node", "build/index.js"]
